# Generated by Django 3.2.10 on 2022-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0002_auto_20220928_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('celular', models.CharField(max_length=250, null=True)),
                ('fecha_nacimiento', models.CharField(max_length=250, null=True)),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('correo_electronico', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
